name: "Daily check and update"

on:
  schedule:
    - cron: "16 16 * * *"
  workflow_dispatch:

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install requirements
        run: |-
          pip install -r requirements.txt

      - name: Run hoyolab.py
        env:
          COOKIE: ${{ secrets.COOKIE }}
          USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          RUN_ONCE: True
        run: |-
          python3 ./hoyolab.py

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "katheryne@bot.op"
          git config --global user.name "Katheryne"
          git add -A
          git commit -m "Updated content" || exit 0
          git push
